version: '3'
services:

  server:
    container_name: waproject-ebay-server
    build:
      context: ./server
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./server:/server
      - ./server/docker/dev/start.sh:/usr/local/bin/start.sh
    ports:
      - 3001:3001
      - 3009:9229
    environment:
      - NODE_ENV=production
      - MONGO_DSN=mongodb://mongodb:27017/ebay
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - EBAY_KEY=DanielPr-E-PRD-af2fb35bc-c4a44b17
      - MAILGUN_FROM=
      - MAILGUN_APIKEY=
      - MAILGUN_DOMAIN=
    links:
      - mongodb

  front:
    container_name: waproject-ebay-front
    build:
      context: ./front
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./front:/front
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production

  mongodb:
    container_name: waproject-ebay-mongo
    image: mongo
    container_name: mongodb
    ports:
      - 3003:27017
    volumes:
      - ./.docker-data/mongodb:/data/db