version: '3'
services:

  mongodb:
    container_name: waproject-ebay-mongo
    image: mongo
    container_name: mongodb
    ports:
      - 3003:27017
    volumes:
      - ./.docker-data/mongodb:/data/db