version: '3'
services:

  server:
    container_name: waproject-ebay-server
    build:
      context: ./server
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./server:/server
      - ./server/docker/dev/start.sh:/usr/local/bin/start.sh
    ports:
      - 3001:3000
      - 3009:9229
    environment:
      - NODE_ENV=development
      - MONGO_DSN=mongodb://mongodb:27017/contactcenter
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    links:
      - mongodb

  front:
    container_name: waproject-ebay-front
    build:
      context: ./front
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./front:/front:cached
    ports:
      - 3002:3000
    environment:
      - NODE_ENV=development

  mongodb:
    container_name: waproject-ebay-mongo
    image: mongo
    container_name: mongodb
    ports:
      - 3003:27017
    volumes:
      - ./.docker-data/mongodb:/data/db